(function(){
'use strict';

var SUBJECTS=[
  {id:'mathematics',code:'MAT',name:'Mathematics',desc:'Number systems, complex numbers, sequences, equations and inequalities.',chapters:[
    C('math1',1,'Real Number System',[
      T('Sets','Notation, subset, equality, union and intersection.','A set is a collection of distinct objects. Subset means every element is included in another set.',['Recognise elements, empty set, subset, union and intersection.','Use set notation carefully: empty set is not the same as {0}.','Union means either set; intersection means common elements.']),
      T('Number Sets','Natural, whole, integer, rational, irrational and real numbers.','Rational numbers can be written as a/b where b is not zero; irrational numbers cannot.',['Classify a number into N, W, Z, Q, irrational or R.','Whole numbers include 0, natural numbers usually start from 1.','Every rational and irrational number is real.']),
      T('Intervals','Number line and interval notation.','Round brackets exclude endpoints; square brackets include endpoints.',['(a,b) means a < x < b.','[a,b] means a <= x <= b.','Infinity is never included with square brackets.']),
      T('Linear Inequalities','Solve inequalities and represent solution sets.','Multiplying or dividing by a negative value reverses the inequality sign.',['Add or subtract both sides without changing direction.','Multiply or divide by positive values without changing direction.','Flip the sign when multiplying or dividing by a negative value.']),
      T('Indices, Surds and Logarithms','Power laws, roots, rationalising and logarithm laws.','Use index laws, surd conjugates and log laws to simplify expressions.',['a^m a^n = a^(m+n).','a^(-n)=1/a^n for a not zero.','log_a(mn)=log_a(m)+log_a(n).'])
    ],['S subset T: every element of S is in T','(a,b): a < x < b','[a,b]: a <= x <= b','a^m a^n = a^(m+n)','log_a(mn)=log_a(m)+log_a(n)']),
    C('math2',2,'Complex Numbers',[
      T('Imaginary Unit','i squared equals negative one and z is written as a+bi.','The imaginary unit i is defined by i^2=-1.',['Complex numbers extend the real number system.','z=a+bi where a is the real part and b is the imaginary coefficient.','Pure imaginary means real part is zero.']),
      T('Operations','Equality, addition, subtraction and multiplication.','Compare real parts with real parts and imaginary parts with imaginary parts.',['a+bi=c+di only when a=c and b=d.','Add and subtract by collecting like parts.','In multiplication, expand then replace i^2 with -1.']),
      T('Conjugates','Use conjugates to divide complex numbers.','The conjugate of a+bi is a-bi.',['Conjugates change the sign of the imaginary part.','z times conjugate(z)=a^2+b^2.','Multiply by the denominator conjugate to make denominator real.']),
      T('Argand, Modulus and Argument','Plot z=a+bi as point (a,b).','The modulus is |z|=sqrt(a^2+b^2).',['Real axis is horizontal and imaginary axis is vertical.','Argument is the angle from the positive real axis.','Adjust the angle according to the quadrant.']),
      T('Polar Form','Write z as r(cos theta+i sin theta).','Polar form uses modulus r and argument theta.',['a=r cos theta and b=r sin theta.','Convert rectangular to polar using r and theta.','Keep degree/radian units consistent.'])
    ],['i^2=-1','z=a+bi','conjugate(a+bi)=a-bi','|z|=sqrt(a^2+b^2)','z=r(cos theta+i sin theta)']),
    C('math3',3,'Sequence',[
      T('Introduction to Sequences','A sequence is an ordered list of terms.','The nth term is commonly written as a_n.',['Sequences can be finite or infinite.','Terms follow a pattern or rule.','A sequence may be explicit or recursive.']),
      T('General Terms','Find formulas that reproduce the pattern.','Look for differences, ratios, powers and alternating signs.',['Alternating signs often use powers of -1.','Check the formula with several terms.','A correct formula must match the order of terms.']),
      T('Arithmetic Sequence','Terms change by a constant difference.','Arithmetic nth term: a_n=a_1+(n-1)d.',['Common difference is d.','Add the same value to move to the next term.','Arithmetic sum uses n/2[2a_1+(n-1)d].']),
      T('Geometric Sequence','Terms change by a constant ratio.','Geometric nth term: a_n=a_1r^(n-1).',['Common ratio is r.','Multiply by the same value to move to the next term.','Finite geometric sum uses a_1(1-r^n)/(1-r).'])
    ],['a_n is the nth term','Arithmetic: a_n=a_1+(n-1)d','Arithmetic sum: S_n=n/2[2a_1+(n-1)d]','Geometric: a_n=a_1r^(n-1)','Geometric sum: S_n=a_1(1-r^n)/(1-r)']),
    C('math4',4,'Equations, Inequalities and Absolute Values',[
      T('Equations','Solve equations by preserving equality.','Do the same operation to both sides and check by substitution.',['Isolate the unknown carefully.','Substitution confirms the solution.','Algebraic manipulation must preserve equality.']),
      T('Quadratic Equations','Use factorisation, completing square or quadratic formula.','A quadratic equation has degree 2.',['Factorisation is fastest when factors are obvious.','The quadratic formula solves ax^2+bx+c=0.','The discriminant helps identify solution type.']),
      T('Inequalities','Solve and represent solution sets.','Multiplying or dividing by a negative reverses the inequality sign.',['Solutions can be shown using intervals.','Compound inequalities must satisfy all conditions.','Check boundary points carefully.']),
      T('Absolute Values','Interpret absolute value as distance from zero.','|x-a|<b means the distance from a is less than b.',['|x| is never negative.','|x|=a gives x=a or x=-a when a>=0.','Split absolute value problems into cases.'])
    ],['Quadratic formula: x=(-b±sqrt(b^2-4ac))/(2a)','Multiply/divide by negative reverses inequality','|x|=a gives x=±a','|x-a|<b means a-b<x<a+b'])
  ]},
  {id:'chemistry',code:'ASC0304',name:'Chemistry I',desc:'Matter, measurement, mole concept, solutions, reactions and atomic structure.',chapters:[
    C('chem1',1,'Matter and Measurement',[
      T('Matter and Properties','Matter has mass and occupies space.','Matter is anything that has mass and volume.',['Physical properties can be observed without changing identity.','Chemical properties describe ability to form new substances.','Density is a physical property.']),
      T('Classification of Matter','Classify elements, compounds and mixtures.','Mixtures can be separated by physical methods.',['Elements contain one type of atom.','Compounds contain chemically combined elements.','Mixtures may be homogeneous or heterogeneous.']),
      T('SI Units','Use standard units and conversions.','Measurements need both value and unit.',['SI units make scientific communication consistent.','Unit conversion uses conversion factors.','Always track units through calculations.']),
      T('Significant Figures','Report measurements with appropriate precision.','Significant figures reflect measurement precision.',['Measured values should not imply false precision.','Rounding should follow calculation rules.','Zeros may or may not be significant depending on position.'])
    ],['Matter has mass and occupies space','Elements contain one type of atom','Compounds have fixed composition','Density = mass/volume','SI units standardise measurements']),
    C('chem2',2,'Atomic Mass, Mole Concept and Concentration',[
      T('Atomic Mass and Isotopes','Relative masses and isotope abundance.','Isotopes have same proton number but different neutron number.',['Average atomic mass depends on isotope abundance.','Atoms are small, so relative atomic mass is used.','Mass number equals protons plus neutrons.']),
      T('Mole Concept','Connect particles, mass and amount.','One mole contains Avogadro number of particles.',['Molar mass connects mass and moles.','n = mass / molar mass.','Use mole as a counting unit for particles.']),
      T('Molarity','Express concentration as moles per litre.','Molarity M = n/V where V is in litres.',['Convert volume to litres before using molarity.','More moles in the same volume means higher concentration.','Molarity is common for solutions.']),
      T('Dilution','Prepare lower concentration solutions.','During dilution, moles of solute remain constant.',['Adding solvent lowers concentration.','Use M1V1=M2V2.','Volumetric glassware improves accuracy.'])
    ],['Avogadro number = 6.022 x 10^23','n = mass / molar mass','M = n/V(L)','M1V1=M2V2']),
    C('chem3',3,'Chemical Equations and Stoichiometry',[
      T('Chemical Equations','Represent reactants and products.','Balanced equations conserve atoms.',['Reactants are on the left and products on the right.','State symbols may show physical states.','Balance equations before calculation.']),
      T('Mole Ratio','Use coefficients to relate amounts.','Coefficients in balanced equations give mole ratios.',['Mole ratios connect known and unknown substances.','Never use mole ratio from an unbalanced equation.','Coefficients compare amounts in moles.']),
      T('Limiting Reagent','Find the reactant that runs out first.','The limiting reagent determines maximum product.',['Excess reagent remains after reaction.','Compare possible products from each reactant.','The limiting reagent controls yield.']),
      T('Yield','Compare theoretical and actual product.','Percentage yield = actual/theoretical x 100%.',['Theoretical yield is calculated from stoichiometry.','Actual yield is obtained experimentally.','Low yield may come from side reactions or loss.'])
    ],['Balance equations first','Use coefficients as mole ratios','Limiting reagent gives maximum product','% yield = actual/theoretical x 100%']),
    C('chem4',4,'Atomic Structure',[
      T('Subatomic Particles','Protons, neutrons and electrons.','Atomic number equals number of protons.',['Protons are positive.','Neutrons are neutral.','Electrons are negative.']),
      T('Isotopes','Same element, different neutrons.','Isotopes have same proton number but different neutron number.',['Isotopes have different mass numbers.','Isotope abundance affects average atomic mass.','Chemical identity depends on proton number.']),
      T('Electron Arrangement','Electrons occupy shells or energy levels.','Valence electrons are outer shell electrons.',['Electron arrangement explains chemical behaviour.','Elements in the same group often share valence patterns.','Outer electrons influence bonding.']),
      T('Periodic Table Link','Atomic structure explains periodicity.','The periodic table is arranged by atomic number.',['Groups show similar properties.','Periods show occupied energy levels.','Atomic number increases across the table.'])
    ],['Atomic number = protons','Mass number = protons + neutrons','Isotopes differ in neutrons','Valence electrons influence bonding'])
  ]},
  {id:'biology',code:'ASB0204',name:'Biology I',desc:'Molecules of life and cell structure/function.',chapters:[
    C('bio2',2,'Molecules of Life',[
      T('Water','Polarity, hydrogen bonding and biological importance.','Water is polar and forms hydrogen bonds.',['Water is a good solvent for many polar substances.','Water helps regulate temperature.','Cohesion and adhesion support biological processes.']),
      T('Carbohydrates','Sugars, starch and energy storage.','Carbohydrates provide energy and structural support.',['Monosaccharides are simple sugars.','Polysaccharides include starch, glycogen and cellulose.','Glucose is an important energy source.']),
      T('Lipids','Fats, oils, phospholipids and steroids.','Lipids are hydrophobic and store energy.',['Phospholipids form cell membrane bilayers.','Fats store long-term energy.','Steroids are lipid-based molecules.']),
      T('Proteins','Amino acid polymers with many functions.','Proteins are made of amino acids.',['Protein shape affects function.','Enzymes speed up biological reactions.','Proteins can be structural, transport or signalling molecules.']),
      T('Nucleic Acids','DNA and RNA store and use genetic information.','Nucleic acids are made of nucleotides.',['DNA stores hereditary information.','RNA helps in protein synthesis.','Nucleotides contain sugar, phosphate and nitrogenous base.'])
    ],['Water is polar','Carbohydrates provide energy','Lipids form membranes','Proteins are made of amino acids','DNA and RNA are nucleic acids']),
    C('bio3',3,'Cell Structure and Function',[
      T('Cell Theory','Cells are the basic unit of life.','All cells arise from pre-existing cells.',['All organisms are made of cells.','Cells are structural and functional units.','New cells come from existing cells.']),
      T('Prokaryotic and Eukaryotic Cells','Compare cell organisation.','Prokaryotes lack a membrane-bound nucleus.',['Eukaryotes have nucleus and membrane-bound organelles.','Bacteria are prokaryotes.','Plant and animal cells are eukaryotic.']),
      T('Cell Membrane','Selective barrier around the cell.','The plasma membrane is selectively permeable.',['The membrane controls entry and exit.','Phospholipid bilayer is the main structure.','Membrane proteins support transport and signalling.']),
      T('Organelles','Specialised structures with functions.','Mitochondria produce ATP.',['Nucleus stores genetic material.','Ribosomes synthesize proteins.','Chloroplasts perform photosynthesis in plant cells.']),
      T('Cytoskeleton','Support, shape and transport.','The cytoskeleton maintains cell shape and supports movement.',['Microtubules and microfilaments are components.','It supports intracellular transport.','It helps organise the cell.'])
    ],['Cells are basic unit of life','Prokaryotes lack membrane-bound nucleus','Membrane is selectively permeable','Ribosomes synthesize proteins','Mitochondria produce ATP'])
  ]},
  {id:'agriculture',code:'ASA0104',name:'Agriculture Industry',desc:'Agriculture industry, national importance and crop production.',chapters:[
    C('agri1',1,'Introduction and Importance of Agricultural Industry',[
      T('Definition of Agriculture','Cultivation and production of useful crops, animals and aquatic products.','Agriculture includes crops, livestock and aquatic production systems.',['Agriculture supplies food and raw materials.','It involves production, harvest and marketing.','It supports livelihoods and industry.']),
      T('Importance to Country','Agriculture supports food security and the economy.','Food security is a major national reason for agriculture.',['Agriculture creates employment and income.','It reduces overdependence on imports.','It supports rural development.']),
      T('Agriculture Sectors','Agro-food, commodities and support systems.','Agro-food is linked to national food supply.',['Agriculture includes diverse crops and commodities.','Support systems include research, extension and marketing.','Sectors work together in the value chain.']),
      T('Agencies and Roles','Institutions support development and regulation.','Agencies support productivity, research and regulation.',['Extension services help farmers apply better practices.','Research improves productivity.','Regulation protects quality and sustainability.'])
    ],['Agriculture includes crops, animals and aquatic systems','Food security is a national priority','Agencies support productivity and development']),
    C('agri2',2,'Crop Production',[
      T('Cropping Pattern','Arrangement of crops in a land area.','Cropping pattern describes how crops are arranged in the field.',['Good layout improves use of space and light.','Pattern affects management and harvesting.','Spacing reduces competition.']),
      T('Cropping System','How crops are grown across time and space.','Intercropping means growing two or more crops together.',['Cropping systems consider crop sequence and combination.','Good systems reduce competition and improve resource use.','Crop rotation can reduce pest and disease pressure.']),
      T('Plant Necessities','Medium, nutrients, water, light and protection.','Plants need suitable medium, nutrients, water and light.',['Fertiliser supplies nutrients.','Water management affects growth.','Light supports photosynthesis.']),
      T('Crop Management','Spacing, fertiliser and pest control.','Good crop management protects yield and quality.',['Spacing influences competition.','Pest and disease control reduces crop losses.','Management decisions affect productivity.'])
    ],['Cropping pattern = crop arrangement','Intercropping = two or more crops together','Fertiliser supplies nutrients','Pest management protects yield'])
  ]},
  {id:'physics',code:'PHY',name:'Physics',desc:'Physics content will be activated when files are added.',chapters:[]}
];

function T(title,summary,core,notes){return{title:title,summary:summary,core:core,notes:notes||[]};}
function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
function C(id,n,title,topics,rules){var out=[];for(var i=0;i<topics.length;i++){var topic=topics[i];topic.id=id+'-'+slug(topic.title);topic.rule=rules[i%rules.length];out.push(topic);}return{id:id,number:n,title:title,topics:out,rules:rules};}

var KEY='skorasasi1_mastery_v5';
var state=load();
var activeSubject=state.activeSubject||firstLiveSubject().id;
var activeChapter=state.activeChapter||firstChapter(subject(activeSubject)).id;
var activeTopic=null;
var quizSession=null;
var challengeSession=null;

function $(id){return document.getElementById(id);}
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
function closest(el,sel){while(el&&el.nodeType===1){if(el.matches&&el.matches(sel))return el;el=el.parentElement;}return null;}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{};}catch(e){return{};}}
function save(){state.activeSubject=activeSubject;state.activeChapter=activeChapter;try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}}
function liveSubjects(){var arr=[];for(var i=0;i<SUBJECTS.length;i++)if(SUBJECTS[i].chapters.length)arr.push(SUBJECTS[i]);return arr;}
function firstLiveSubject(){return liveSubjects()[0];}
function subject(id){for(var i=0;i<SUBJECTS.length;i++)if(SUBJECTS[i].id===id)return SUBJECTS[i];return firstLiveSubject();}
function firstChapter(s){return s&&s.chapters&&s.chapters[0];}
function chapter(id){for(var i=0;i<SUBJECTS.length;i++)for(var j=0;j<SUBJECTS[i].chapters.length;j++)if(SUBJECTS[i].chapters[j].id===id)return SUBJECTS[i].chapters[j];return firstChapter(subject(activeSubject));}
function chapterSubject(ch){for(var i=0;i<SUBJECTS.length;i++)for(var j=0;j<SUBJECTS[i].chapters.length;j++)if(SUBJECTS[i].chapters[j].id===ch.id)return SUBJECTS[i];return subject(activeSubject);}
function allChapters(){var arr=[];for(var i=0;i<SUBJECTS.length;i++)for(var j=0;j<SUBJECTS[i].chapters.length;j++)arr.push(SUBJECTS[i].chapters[j]);return arr;}
function progress(c){state.progress=state.progress||{};state.progress[c.id]=state.progress[c.id]||{topics:{},answered:0,correct:0,sessions:0};for(var i=0;i<c.topics.length;i++){state.progress[c.id].topics[c.topics[i].id]=state.progress[c.id].topics[c.topics[i].id]||{attempts:0,correct:0};}return state.progress[c.id];}
function topicProgress(c,t){var p=progress(c).topics[t.id];var acc=p.attempts?Math.round((p.correct/p.attempts)*100):0;var pct=0,label='Not started';if(p.attempts>0){pct=30;label='Attempted';}if(p.attempts>=4&&acc>=65){pct=55;label='Familiar';}if(p.attempts>=8&&acc>=75){pct=78;label='Proficient';}if(p.attempts>=12&&acc>=85){pct=100;label='Mastered';}return{attempts:p.attempts,correct:p.correct,acc:acc,pct:pct,label:label};}
function chapterScore(c){var total=0,mastered=0,p=progress(c);for(var i=0;i<c.topics.length;i++){var tp=topicProgress(c,c.topics[i]);total+=tp.pct;if(tp.label==='Mastered')mastered++;}return{mastery:Math.round(total/c.topics.length),answered:p.answered||0,correct:p.correct||0,accuracy:p.answered?Math.round((p.correct/p.answered)*100):0,mastered:mastered,total:c.topics.length};}
function subjectScore(s){if(!s.chapters.length)return{mastery:0,answered:0};var total=0,answered=0;for(var i=0;i<s.chapters.length;i++){var cs=chapterScore(s.chapters[i]);total+=cs.mastery;answered+=cs.answered;}return{mastery:Math.round(total/s.chapters.length),answered:answered};}
function semesterScore(){var ls=liveSubjects(),total=0;for(var i=0;i<ls.length;i++)total+=subjectScore(ls[i]).mastery;return ls.length?Math.round(total/ls.length):0;}
function statsTop(){var el=$('topStats');if(!el)return;var s=subject(activeSubject),c=chapter(activeChapter),ss=subjectScore(s),cs=chapterScore(c);el.innerHTML='<span class="chip">Semester <b>'+semesterScore()+'%</b></span><span class="chip">'+esc(s.code)+' <b>'+ss.mastery+'%</b></span><span class="chip">Chapter <b>'+cs.mastery+'%</b></span>';}
function shuffle(arr){var a=arr.slice();for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),tmp=a[i];a[i]=a[j];a[j]=tmp;}return a;}
function sample(arr,n){return shuffle(arr).slice(0,Math.min(n,arr.length));}
function otherTopics(c,t){var arr=[];for(var i=0;i<c.topics.length;i++)if(c.topics[i].id!==t.id)arr.push(c.topics[i]);return arr;}
function uniqueChoices(correct,wrongs){var list=[correct],i;for(i=0;i<wrongs.length;i++){if(wrongs[i]&&list.indexOf(wrongs[i])<0)list.push(wrongs[i]);}
var fillers=['Only memorise the title','Skip feedback after answering','Use random formula without checking context','Ignore units and conditions','Read once without retrieval practice'];
for(i=0;list.length<4&&i<fillers.length;i++)if(list.indexOf(fillers[i])<0)list.push(fillers[i]);
return shuffle(list.slice(0,4));}
function Q(c,t,type,prompt,correct,wrongs,explain){var choices=uniqueChoices(correct,wrongs||[]);return{chapterId:c.id,topicId:t.id,type:type,prompt:prompt,choices:choices,answer:choices.indexOf(correct),explain:explain||correct};}
function questionBank(c,t){
var others=otherTopics(c,t),otherCores=[],otherTitles=[],otherSummaries=[],otherRules=[],i;
for(i=0;i<others.length;i++){otherCores.push(others[i].core);otherTitles.push(others[i].title);otherSummaries.push(others[i].summary);otherRules.push(others[i].rule);}
var chapters=allChapters(),chapterTitles=[];for(i=0;i<chapters.length;i++)if(chapters[i].id!==c.id)chapterTitles.push('Chapter '+chapters[i].number+': '+chapters[i].title);
var subjectName=chapterSubject(c).name;
var bank=[];
bank.push(Q(c,t,'Recall','Which statement best explains '+t.title+'?',t.core,otherCores,'Core idea: '+t.core));
bank.push(Q(c,t,'Concept','What is the main focus of '+t.title+'?',t.summary,otherSummaries,'Focus: '+t.summary));
bank.push(Q(c,t,'Key fact','Which key fact should be linked with '+t.title+'?',t.rule,otherRules,'Remember this key fact: '+t.rule));
bank.push(Q(c,t,'Identify','This fact belongs to which topic: '+t.core+'?',t.title,otherTitles,'That fact is under '+t.title+'.'));
bank.push(Q(c,t,'Chapter link','Where does '+t.title+' belong?',subjectName+' · Chapter '+c.number+': '+c.title,chapterTitles,'It belongs in '+subjectName+' Chapter '+c.number+'.'));
bank.push(Q(c,t,'Method','What is the best way to master '+t.title+'?', 'Explain it in your own words, answer questions, then check feedback.', ['Read once and move on','Only memorise the title','Skip the explanation after a wrong answer'], 'Mastery needs retrieval practice and feedback.'));
bank.push(Q(c,t,'Mistake','Which habit most likely weakens understanding of '+t.title+'?', 'Using the rule without checking the condition or context.', ['Writing the key fact clearly','Comparing it with nearby topics','Doing short repeated practice'], 'Common mistakes happen when a rule is applied without context.'));
bank.push(Q(c,t,'Application','When a question mentions '+t.title+', what should you do first?', 'Identify the relevant definition, rule or relationship before calculating.', ['Guess the answer immediately','Use any formula from another chapter','Ignore the given condition'], 'Start from the concept before applying steps.'));
bank.push(Q(c,t,'Feedback','After getting '+t.title+' wrong, what should you review?', 'The explanation, the key fact and why the wrong option is tempting.', ['Only the final score','The app design','Unrelated topics first'], 'Feedback turns mistakes into mastery.'));
bank.push(Q(c,t,'Retention','What helps long-term retention for '+t.title+'?', 'Short repeated practice across time.', ['One long reading without quiz','Avoiding difficult questions','Only looking at notes during tests'], 'Spacing and retrieval improve retention.'));
bank.push(Q(c,t,'Compare','Which neighbouring topic is most important to compare with '+t.title+'?', others[0]?others[0].title:t.title, otherTitles.slice(1), 'Compare related topics so the boundary is clear.'));
bank.push(Q(c,t,'Mastery check','A student has mastered '+t.title+' when they can...', 'Recall the idea, apply it correctly and explain the reason.', ['Recognise the title only','Copy the answer without understanding','Avoid mixed questions'], 'Mastery means recall, application and explanation.'));
return bank;
}
function allQuestionsForChapter(c){var out=[];for(var i=0;i<c.topics.length;i++)out=out.concat(questionBank(c,c.topics[i]));return out;}
function findTopic(c,id){for(var i=0;i<c.topics.length;i++)if(c.topics[i].id===id)return c.topics[i];return c.topics[0];}
function findQuestionContext(q){var c=chapter(q.chapterId),t=findTopic(c,q.topicId);return{c:c,t:t};}
function record(q,ok){var ctx=findQuestionContext(q),p=progress(ctx.c),tp=p.topics[ctx.t.id];tp.attempts++;if(ok)tp.correct++;p.answered++;if(ok)p.correct++;p.last=new Date().toISOString();save();statsTop();}
function setActive(sid,cid){var s=subject(sid);if(!s.chapters.length)return;activeSubject=s.id;activeChapter=cid||s.chapters[0].id;activeTopic=null;quizSession=null;challengeSession=null;save();render();}
function optionSubjects(){var a=liveSubjects(),h='';for(var i=0;i<a.length;i++)h+='<option value="'+esc(a[i].id)+'" '+(a[i].id===activeSubject?'selected':'')+'>'+esc(a[i].code+' · '+a[i].name)+'</option>';return h;}
function optionChapters(){var s=subject(activeSubject),h='';for(var i=0;i<s.chapters.length;i++){var c=s.chapters[i];h+='<option value="'+esc(c.id)+'" '+(c.id===activeChapter?'selected':'')+'>Chapter '+c.number+': '+esc(c.title)+'</option>';}return h;}
function toolbar(){var c=chapter(activeChapter),cs=chapterScore(c);return '<div class="contextbar"><div><span class="eyebrow">Current path</span><strong>'+esc(subject(activeSubject).code)+' · Chapter '+c.number+'</strong><small>'+esc(c.title)+'</small></div><div class="contextMeters"><span>'+cs.mastery+'% mastery</span><div class="miniMeter"><i style="width:'+cs.mastery+'%"></i></div></div></div><div class="toolbar"><div><label>Subject</label><select id="subjectPick">'+optionSubjects()+'</select></div><div><label>Chapter</label><select id="chapterPick">'+optionChapters()+'</select></div><button class="btn dark" id="openLearn">Open</button></div>';}
function showView(view){var views=document.querySelectorAll('.view');for(var i=0;i<views.length;i++)views[i].classList.toggle('on',views[i].id===view);var tabs=document.querySelectorAll('.tabs button');for(i=0;i<tabs.length;i++)tabs[i].classList.toggle('on',tabs[i].getAttribute('data-view')===view);render();window.scrollTo({top:0,behavior:'smooth'});}
function renderHome(){var c=chapter(activeChapter),weak=c.topics[0],i;for(i=0;i<c.topics.length;i++)if(topicProgress(c,c.topics[i]).pct<topicProgress(c,weak).pct)weak=c.topics[i];var totalQuestions=0,chs=allChapters();for(i=0;i<chs.length;i++)totalQuestions+=allQuestionsForChapter(chs[i]).length;
$('home').innerHTML='<div class="hero"><div><p class="badge">Semester 1 Learning Centre</p><h1>Study by subject. Master by chapter.</h1><p>Layout sudah dikemas untuk belajar laju: pilih subject, masuk chapter, baca ringkas, jawab topic drill, kemudian test dengan mixed challenge.</p><div class="actions"><button class="btn" data-go="subjects">Browse Subjects</button><button class="btn dark" data-go="learn">Continue Learning</button><button class="btn ghost" data-go="challenge">Start Challenge</button></div></div><div class="score"><span>Semester mastery</span><b>'+semesterScore()+'%</b><small>'+chs.length+' live chapters · '+totalQuestions+'+ question pool</small></div></div><div class="statgrid"><div class="stat"><span>Live chapters</span><b>'+chs.length+'</b></div><div class="stat"><span>Question pool</span><b>'+totalQuestions+'</b></div><div class="stat"><span>Current accuracy</span><b>'+chapterScore(c).accuracy+'%</b></div><div class="stat"><span>Next weak topic</span><b>'+esc(weak.title)+'</b></div></div><section class="panel coach"><div><h2>Recommended flow</h2><p>Learn one topic, answer 10 focused questions, then run 12-question mixed challenge. Repeat weak topics until mastery naik.</p></div><div class="flow"><span>1 Learn</span><span>2 Topic Drill</span><span>3 Mixed Challenge</span><span>4 Weak Review</span></div></section>';
}
function renderSubjects(){var h='<div class="sectionHead"><div><h2>Semester 1 Subjects</h2><p>Setiap card tunjuk progress dan chapter live. Physics masih placeholder sampai file masuk.</p></div></div><div class="grid">';for(var i=0;i<SUBJECTS.length;i++){var s=SUBJECTS[i],sc=subjectScore(s),live=s.chapters.length;h+='<article class="subject"><div class="row"><div class="mark">'+esc(s.code)+'</div><span class="badge '+(live?'':'soon')+'">'+(live?'Live':'Coming soon')+'</span></div><h3>'+esc(s.name)+'</h3><p>'+esc(s.desc)+'</p><div class="meter"><i style="width:'+sc.mastery+'%"></i></div><p class="submeta">'+sc.mastery+'% mastery · '+live+' chapters · '+sc.answered+' answered</p><div class="list chapterList">';if(live){for(var j=0;j<s.chapters.length;j++){var c=s.chapters[j],cc=chapterScore(c);h+='<button class="chapter" data-open="'+s.id+'|'+c.id+'"><span><b>Chapter '+c.number+'</b><small>'+esc(c.title)+'</small></span><strong>'+cc.mastery+'%</strong></button>';}}else h+='<div class="empty">Content pending</div>';h+='</div></article>';}h+='</div>';$('subjects').innerHTML=h;}
function renderLearn(){var c=chapter(activeChapter);if(!activeTopic)activeTopic=c.topics[0].id;var cur=findTopic(c,activeTopic),list='',notes='',rules='',i;for(i=0;i<c.topics.length;i++){var t=c.topics[i],tp=topicProgress(c,t);list+='<button class="topic '+(t.id===cur.id?'on':'')+'" data-topic="'+esc(t.id)+'"><span>'+esc(t.title)+'</span><small>'+tp.label+' · '+tp.acc+'%</small></button>';}for(i=0;i<cur.notes.length;i++)notes+='<div class="note"><b>'+String(i+1).padStart(2,'0')+'</b><span>'+esc(cur.notes[i])+'</span></div>';for(i=0;i<c.rules.length;i++)rules+='<div class="rule">'+esc(c.rules[i])+'</div>';
$('learn').innerHTML=toolbar()+'<div class="sectionHead"><div><h2>Learn</h2><p>'+esc(subject(activeSubject).name)+' · Chapter '+c.number+': '+esc(c.title)+'</p></div><button class="btn ghost" data-go="practice">Go Practice</button></div><div class="layout"><aside class="topicRail">'+list+'</aside><article class="lesson"><div class="lessonTop"><span class="badge">Topic focus</span><div class="topicScore">'+topicProgress(c,cur).pct+'%</div></div><h2>'+esc(cur.title)+'</h2><p>'+esc(cur.summary)+'</p><div class="concept"><h3>Core idea</h3><p>'+esc(cur.core)+'</p></div><h3>What to remember</h3>'+notes+'<h3>Rules / key facts</h3><div class="rules">'+rules+'</div><div class="actions stickyActions"><button class="btn" data-practice="'+esc(cur.id)+'">Start 10-question topic drill</button><button class="btn ghost" data-go="challenge">Mixed challenge</button></div></article></div>';
}
function renderPractice(){var c=chapter(activeChapter),opts='',cards='',i;for(i=0;i<c.topics.length;i++){var t=c.topics[i],tp=topicProgress(c,t);opts+='<option value="'+esc(t.id)+'">'+esc(t.title)+'</option>';cards+='<button class="topicCard" data-practice="'+esc(t.id)+'"><b>'+esc(t.title)+'</b><span>'+tp.label+' · '+tp.attempts+' attempts · '+tp.acc+'%</span><div class="miniMeter"><i style="width:'+tp.pct+'%"></i></div></button>';}
$('practice').innerHTML=toolbar()+'<div class="sectionHead"><div><h2>Practice</h2><p>By-topic quiz sekarang 10 soalan. Ada juga Weak Drill untuk ulang topik paling lemah dalam chapter.</p></div></div><div class="practiceGrid"><aside class="panel"><label>Topic drill</label><select id="topicPick">'+opts+'</select><button class="btn" id="startQuiz" style="width:100%;margin-top:12px">Start 10 Topic Questions</button><button class="btn ghost" id="weakDrill" style="width:100%;margin-top:10px">Drill Weak Topics</button><div class="topicCards">'+cards+'</div></aside><article class="quizbox" id="quizBox"><div class="empty"><h3>Ready for focused practice?</h3><p>Pilih topik, jawab 10 soalan, dan app akan update mastery berdasarkan jawapan betul/salah.</p></div></article></div>';
}
function renderChallenge(){var c=chapter(activeChapter),subjectChapters=subject(activeSubject).chapters.length,totalPool=0,i;for(i=0;i<allChapters().length;i++)totalPool+=allQuestionsForChapter(allChapters()[i]).length;$('challenge').innerHTML=toolbar()+'<div class="sectionHead"><div><h2>Mixed Challenge</h2><p>12 soalan setiap sesi, tapi pool soalan jauh lebih besar. Sesuai untuk test kefahaman selepas belajar.</p></div></div><div class="challengeGrid"><section class="panel"><label>Challenge scope</label><select id="scope"><option value="current">Current chapter: '+esc(c.title)+'</option><option value="subject">All '+subjectChapters+' chapters in '+esc(subject(activeSubject).name)+'</option><option value="weak">Weak topics in current chapter</option><option value="all">All live subjects and chapters</option></select><div class="scopeStats"><span>Current pool: '+allQuestionsForChapter(c).length+' questions</span><span>All pool: '+totalPool+' questions</span></div><button class="btn dark" id="startChallenge">Start 12 Questions</button></section><article class="quizbox" id="challengeBox"><div class="empty"><h3>Start when ready.</h3><p>Challenge akan campur recall, concept, application, mistake-check dan mastery-check.</p></div></article></div>';}
function renderProgress(){var h='<div class="sectionHead"><div><h2>Progress</h2><p>Mastery naik berdasarkan attempts, accuracy dan pengulangan. Data disimpan pada device/browser ini.</p></div></div><div class="statgrid"><div class="stat"><span>Semester</span><b>'+semesterScore()+'%</b></div><div class="stat"><span>Subject</span><b>'+subjectScore(subject(activeSubject)).mastery+'%</b></div><div class="stat"><span>Chapter</span><b>'+chapterScore(chapter(activeChapter)).mastery+'%</b></div><div class="stat"><span>Answered</span><b>'+chapterScore(chapter(activeChapter)).answered+'</b></div></div>';for(var i=0;i<SUBJECTS.length;i++){var s=SUBJECTS[i],ss=subjectScore(s);h+='<section class="progressrow"><div class="row"><h3>'+esc(s.code)+' · '+esc(s.name)+'</h3><strong>'+ss.mastery+'%</strong></div><div class="meter"><i style="width:'+ss.mastery+'%"></i></div>';if(s.chapters.length){for(var j=0;j<s.chapters.length;j++){var c=s.chapters[j],cs=chapterScore(c);h+='<div class="chapterProgress"><div><b>Chapter '+c.number+': '+esc(c.title)+'</b><small>'+cs.answered+' answered · '+cs.accuracy+'% accuracy · '+cs.mastered+'/'+cs.total+' topics mastered</small></div><strong>'+cs.mastery+'%</strong></div>';}}else h+='<p>Coming soon</p>';h+='</section>';}$('progress').innerHTML=h;}
function questionsForTopic(c,topicId){return questionBank(c,findTopic(c,topicId));}
function weakTopicIds(c){var arr=c.topics.slice().sort(function(a,b){return topicProgress(c,a).pct-topicProgress(c,b).pct;});return arr.slice(0,Math.min(3,arr.length)).map(function(t){return t.id;});}
function makeSession(questions,count,mode){var qs=sample(questions,count);return{items:qs,index:0,score:0,selected:null,done:false,mode:mode||'practice',started:new Date().toISOString()};}
function drawQuiz(boxId,session){var box=$(boxId);if(!box)return;if(!session||!session.items.length){box.innerHTML='<div class="empty">No questions available.</div>';return;}if(session.done){var pct=Math.round((session.score/session.items.length)*100);box.innerHTML='<div class="complete"><span class="badge">Session complete</span><h2>'+session.score+'/'+session.items.length+' correct</h2><p>Score '+pct+'%. Progress dah disimpan. Ulang lagi untuk naikkan mastery.</p><div class="actions"><button class="btn" data-retry="'+boxId+'">Retry</button><button class="btn ghost" data-go="progress">View Progress</button></div></div>';return;}
var q=session.items[session.index],ctx=findQuestionContext(q),answered=session.selected!==null,choices='',i;for(i=0;i<q.choices.length;i++){choices+='<button class="choice '+(answered&&i===q.answer?'ok':'')+' '+(answered&&i===session.selected&&i!==q.answer?'no':'')+'" data-answer="'+i+'" '+(answered?'disabled':'')+'><span>'+String.fromCharCode(65+i)+'</span><b>'+esc(q.choices[i])+'</b></button>';}
var progressPct=Math.round((session.index/session.items.length)*100);box.innerHTML='<div class="quizMeta"><span class="badge">'+esc(q.type)+'</span><span>Question '+(session.index+1)+'/'+session.items.length+'</span><span>'+esc(chapterSubject(ctx.c).code)+' · Ch '+ctx.c.number+'</span></div><div class="meter"><i style="width:'+progressPct+'%"></i></div><h2 class="question">'+esc(q.prompt)+'</h2><p class="quizTopic">'+esc(ctx.c.title)+' · '+esc(ctx.t.title)+'</p><div class="choices">'+choices+'</div><div class="feedback '+(answered?'show':'')+'">'+(answered?'<b>'+(session.selected===q.answer?'Correct':'Not yet')+'</b><p>'+esc(q.explain)+'</p>':'')+'</div><div class="actions quizActions"><button class="btn" data-next="'+boxId+'" '+(answered?'':'disabled')+'>'+(session.index+1===session.items.length?'Finish':'Next')+'</button></div>';
}
function startTopicQuiz(topicId){var c=chapter(activeChapter),questions=questionsForTopic(c,topicId);quizSession=makeSession(questions,10,'topic');drawQuiz('quizBox',quizSession);}
function startWeakDrill(){var c=chapter(activeChapter),ids=weakTopicIds(c),questions=[],i;for(i=0;i<ids.length;i++)questions=questions.concat(questionsForTopic(c,ids[i]));quizSession=makeSession(questions,10,'weak');drawQuiz('quizBox',quizSession);}
function startChallenge(){var scope=$('scope')?$('scope').value:'current',chapters=[],questions=[],i,j,c=chapter(activeChapter);if(scope==='all')chapters=allChapters();else if(scope==='subject')chapters=subject(activeSubject).chapters.slice();else if(scope==='weak'){var ids=weakTopicIds(c);for(i=0;i<ids.length;i++)questions=questions.concat(questionsForTopic(c,ids[i]));}else chapters=[c];for(i=0;i<chapters.length;i++)for(j=0;j<chapters[i].topics.length;j++)questions=questions.concat(questionBank(chapters[i],chapters[i].topics[j]));challengeSession=makeSession(questions,12,'challenge');drawQuiz('challengeBox',challengeSession);}
function activeView(){var v=document.querySelector('.view.on');return v?v.id:'home';}
function render(){statsTop();renderHome();renderSubjects();var v=activeView();if(v==='learn')renderLearn();if(v==='practice')renderPractice();if(v==='challenge')renderChallenge();if(v==='progress')renderProgress();}

document.addEventListener('click',function(e){var b=closest(e.target,'button');if(!b)return;if(b.getAttribute('data-view')){showView(b.getAttribute('data-view'));return;}if(b.getAttribute('data-go')){showView(b.getAttribute('data-go'));return;}if(b.getAttribute('data-open')){var parts=b.getAttribute('data-open').split('|');setActive(parts[0],parts[1]);showView('learn');return;}if(b.id==='openLearn'){setActive($('subjectPick').value,$('chapterPick').value);showView('learn');return;}if(b.getAttribute('data-topic')){activeTopic=b.getAttribute('data-topic');renderLearn();return;}if(b.getAttribute('data-practice')){var topicId=b.getAttribute('data-practice');showView('practice');setTimeout(function(){var pick=$('topicPick');if(pick)pick.value=topicId;startTopicQuiz(topicId);},50);return;}if(b.id==='startQuiz'){startTopicQuiz($('topicPick').value);return;}if(b.id==='weakDrill'){startWeakDrill();return;}if(b.id==='startChallenge'){startChallenge();return;}if(b.getAttribute('data-answer')){var box=closest(b,'#challengeBox')?'challengeBox':'quizBox';var sess=box==='challengeBox'?challengeSession:quizSession;if(!sess||sess.selected!==null)return;sess.selected=Number(b.getAttribute('data-answer'));var q=sess.items[sess.index],ok=sess.selected===q.answer;if(ok)sess.score++;record(q,ok);drawQuiz(box,sess);return;}if(b.getAttribute('data-next')){var bx=b.getAttribute('data-next');var s=bx==='challengeBox'?challengeSession:quizSession;if(!s)return;if(s.index+1>=s.items.length)s.done=true;else{s.index++;s.selected=null;}drawQuiz(bx,s);return;}if(b.getAttribute('data-retry')){if(b.getAttribute('data-retry')==='challengeBox')startChallenge();else startTopicQuiz($('topicPick')?$('topicPick').value:chapter(activeChapter).topics[0].id);return;}});

document.addEventListener('change',function(e){var el=e.target;if(!el)return;if(el.id==='subjectPick'){var s=subject(el.value);if(s.chapters.length){activeSubject=s.id;activeChapter=s.chapters[0].id;activeTopic=null;save();render();}}if(el.id==='chapterPick'){activeChapter=el.value;activeTopic=null;save();render();}});

try{render();}catch(err){document.body.innerHTML='<main class="app"><div class="empty"><h2>SkorAsasi1 loading issue</h2><p>'+esc(err.message)+'</p></div></main>';}
})();
